services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=test@1234
      - MYSQL_DATABASE=bankapp
    networks:
      - mysqldb-network
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 30s
  
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   container_name: phpmyadmin
  #   depends_on:
  #     mysqldb:
  #       condition: service_healthy
  #   networks:
  #     - mysqldb-network
  #   environment:
  #     PMA_HOST: mysqldb
  #     MYSQL_ROOT_PASSWORD: test122
  #   restart: always

volumes:
  mysql-data:
networks:
  mysqldb-network:
