services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: test122
      MYSQL_DATABASE: docker_db
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysqldb-network
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - mysqldb-network
    environment:
      PMA_HOST: mysqldb
      MYSQL_ROOT_PASSWORD: test122
    restart: always

volumes:
  mysql-data:
networks:
  mysqldb-network:

